/* 2016. 12. 26. */
/* 2016. 12. 26. - 김상겸 */
/* 2016. 12. 26. - 김상겸 - 국고보조통합시스템 테이블 추가 */

CREATE TABLE IF NOT EXISTS `t_ex_anbojo` (
  `comp_seq` varchar(32) DEFAULT NULL COMMENT '귀속 회사 시퀀스',
  `anbojo_seq` int(11) NOT NULL AUTO_INCREMENT COMMENT '국고보조 시퀀스',
  `doc_seq` varchar(32) DEFAULT NULL COMMENT '전자결재 아이디',
  `form_seq` varchar(32) DEFAULT NULL COMMENT '양식 시퀀스',
  `anbojo_stat_code` varchar(32) DEFAULT NULL COMMENT '국고보조 상태 코드',
  `gisu_date` varchar(8) DEFAULT NULL COMMENT '결의일자 ( 회계일자 )',
  `write_seq` int(11) DEFAULT NULL COMMENT '작성자 정보 ( t_ex_anbojo_emp )',
  `json_str` longtext COMMENT '국고보조 JSON 문자열',
  `erp_send_yn` varchar(32) DEFAULT NULL COMMENT '국고보조 ERP 전송 여부',
  `erp_send_seq` varchar(32) DEFAULT NULL COMMENT '국고보조 ERP 전송자',
  `erp_send_date` datetime DEFAULT NULL COMMENT '국고보조 ERP 전송일',
  `create_seq` varchar(32) DEFAULT NULL COMMENT '최초 작성자',
  `create_date` datetime DEFAULT NULL COMMENT '최초 작성일',
  `modify_seq` varchar(32) DEFAULT NULL COMMENT '최종 수정자',
  `modify_date` datetime DEFAULT NULL COMMENT '최종 수정일',
  PRIMARY KEY (`anbojo_seq`)
) ENGINE=INNODB AUTO_INCREMENT=810 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `t_ex_anbojo_abdocu` (
  `anbojo_seq` int(11) NOT NULL COMMENT '국고보조 시퀀스',
  `d_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 시퀀스',
  `erp_comp_seq` varchar(4) NOT NULL COMMENT 'ERP 회사 코드',
  `erp_comp_name` varchar(32) DEFAULT NULL COMMENT 'ERP 회사 명칭',
  `mosf_gisu_dt` varchar(8) NOT NULL COMMENT '집행등록 결의일자',
  `mosf_gisu_sq` int(11) DEFAULT NULL COMMENT '집행등록 결의순번',
  `mosf_pay_fg` varchar(2) NOT NULL COMMENT '지급구분 ( 1 : 일반 / 2 : 인력등록 )',
  `erp_biz_seq` varchar(4) NOT NULL COMMENT 'ERP 사업장 코드',
  `erp_biz_name` varchar(32) DEFAULT NULL COMMENT 'ERP 사업장 명칭',
  `erp_dept_seq` varchar(4) NOT NULL COMMENT 'ERP 부서 코드',
  `erp_dept_name` varchar(32) DEFAULT NULL COMMENT 'ERP 부서 명칭',
  `erp_emp_seq` varchar(10) NOT NULL COMMENT 'ERP 사원 번호',
  `erp_emp_name` varchar(32) DEFAULT NULL COMMENT 'ERP 사원 명',
  `cntc_sn` int(11) DEFAULT NULL COMMENT '연계순번 ( 파일 생성시 update, 파일내 데이터를 구별하는 유일한 식별자_순차적 기재 )',
  `cntc_job_process_code` varchar(2) DEFAULT NULL COMMENT '연계업무처리 코드 ( 등록, 수정, 삭제 요청시 ( C : 등록 / U : 수정 / D : 삭제 ) / 집행등록 요청 시 : C / 집행수정 요청 시 : U / 집행삭제 요청 시 : D )',
  `intrfc_id` varchar(20) DEFAULT NULL COMMENT '인터페이스 ID ( IF-EXE-ERP-0074 )',
  `trnsc_id` varchar(50) DEFAULT NULL COMMENT '트랜잭션 ID ( 파일생성시 update )',
  `file_id` varchar(64) DEFAULT NULL COMMENT '파일 ID ( 파일생성시 update ( 첨부파일이 존재할 경우 ) )',
  `cntc_creat_dt` varchar(14) DEFAULT NULL COMMENT '연계생성일시 ( 파일생성시 update ( yyyymmddhh24miss ) )',
  `cntc_trget_sys_code` varchar(6) NOT NULL COMMENT '연계대상 기관시스템코드 ( 디폴트 : ANBOJO_SYSTEM_CD.SYSTEM_CD )',
  `bsnsyear` varchar(4) NOT NULL COMMENT '사업연도',
  `ddtlbz_id` varchar(20) NOT NULL COMMENT '상세내역 사업 ID',
  `exc_instt_id` varchar(12) NOT NULL COMMENT '수행기관 ID ( 디폴트 : ANBOJO_SYSTEM_CD.BUSINESS_CD )',
  `excut_cntc_id` varchar(20) NOT NULL COMMENT '집행연계 ID ( 집행건별 유일 KEY ( CO_CD + MOSF_GISU_DT + MOSF_GISU_SQ )',
  `excut_ty_se_code` varchar(20) NOT NULL DEFAULT '20' COMMENT '집행 유형 구분 코드 ( 10 : 계약집행 / 20 : 일반집행 ( 연계는 일반집행만 지원 ) )',
  `pruf_se_code` varchar(3) NOT NULL COMMENT '증빙구분 코드 ( 전자세금계산서 : 001 / 전자계산서(면세) : 002 / 카드 : 004 / 기타 : 005 )',
  `card_no` varchar(40) DEFAULT NULL COMMENT '카드번호 ( 증빙구분 카드(004) 인 경우 카드 번호 )',
  `ctr_cd` varchar(10) DEFAULT NULL,
  `pruf_se_no` varchar(55) DEFAULT NULL COMMENT '증빙승인번호 ( 전자세금계산서 승인번호, 카드 매입 추심번호 )',
  `tax_ty` varchar(2) DEFAULT NULL COMMENT '매입매출 구분 ( 증빙구분코드가 전자세금계산서 / 전자계산서인 경우만 적용 ( 매출 : 1 / 매입 : 2 / 면세매출 : 3 / 면세매입 : 4 ) => 결의서 발행 시 과세구분 정의로 활용, 신용카드의 경우 과세구분 : "과세" 로 처리 )',
  `excut_requst_de` varchar(8) NOT NULL COMMENT '증빙사용 일자 ( 전자세금계산서 = 발행일자 / 카드 = 매입일자 / 기타 = 직접입력 )',
  `transfr_acnut_se_code` varchar(3) DEFAULT NULL COMMENT '자계좌입금구분 ( 공통코드 : 1089 ( 거래처계좌입금 : 001 / 자계좌입금 : 002 ) )',
  `sbsacnt_trfrsn_code` varchar(3) DEFAULT NULL COMMENT '자계좌이체사유코드 ( 공통코드 : 0665 ( 교부전집행 : 001 / 운영비 : 002 / 해외송금 : 003 / 카드결제 : 004 / 기타 : 099 ) ) ※자계좌입금구분이''002''이면 해당 항목 필수입력',
  `sbsacnt_trfrsn_cn` varchar(4000) DEFAULT NULL COMMENT '자계좌이체사유 ( 자계좌이체사유코드 기타 ( 099 ) 인 경우 필수 입력',
  `bcnc_se_code` varchar(3) NOT NULL DEFAULT '001' COMMENT '거래처구분 코드 ( 법인거래 : 001 / 개인사업자거래 : 002 / 개인거래 : 003 )',
  `tr_cd` varchar(10) DEFAULT NULL COMMENT '거래처 코드 ( 거래처실명번호와 매칭된 STRADE 의 TR_CD ( 코드도움을 통한 변경 가능 ) )',
  `bcnc_lsft_no` varchar(24) DEFAULT NULL COMMENT '거래처 실명 번호 ( 법인, 개인사업자 - 사업자번호 / 개인 - 생년월일 + 성별 )',
  `bcnc_cmpny_nm` varchar(300) DEFAULT NULL COMMENT '거래처 회사명',
  `bcnc_induty_nm` varchar(300) DEFAULT NULL COMMENT '거래처 업종명',
  `bcnc_bizcnd_nm` varchar(300) DEFAULT NULL COMMENT '거래처 업태명',
  `bcnc_rprsntv_nm` varchar(300) DEFAULT NULL COMMENT '거래처 대표자명',
  `bcnc_adres` varchar(500) DEFAULT NULL COMMENT '거래처 주소',
  `bcnc_telno` varchar(14) DEFAULT NULL COMMENT '거래처 전화번호',
  `bcnc_bank_code` varchar(3) DEFAULT NULL COMMENT '거래처 입금은행 코드',
  `duzon_bank_code` varchar(10) DEFAULT NULL COMMENT '거래처 입금은행 코드 ( 더존 )',
  `bcnc_acnut_no` varchar(20) DEFAULT NULL COMMENT '거래처 입금계좌번호',
  `excut_splpc` decimal(15,0) DEFAULT NULL COMMENT '집행 공급가액',
  `excut_vat` decimal(15,0) DEFAULT NULL COMMENT '집행 부가가치세',
  `excut_sum_amount` decimal(15,0) DEFAULT NULL COMMENT '집행 합계금액',
  `excut_prpos_cn` varchar(400) DEFAULT NULL COMMENT '집행 용도 내용',
  `bcnc_bnkb_indict_cn` varchar(20) DEFAULT NULL COMMENT '거래처 통장 표시 내용',
  `sbsidy_bnkb_indict_cn` varchar(20) DEFAULT NULL COMMENT '보조금 통장 표시 내용',
  `prepar` varchar(100) DEFAULT NULL COMMENT '예비',
  `excut_expitm_taxitm_cnt` varchar(5) DEFAULT NULL COMMENT '집행별 비목세목 건 수',
  `send_yn` varchar(3) DEFAULT NULL COMMENT '전송 상태 값',
  `process_result_code` varchar(4) DEFAULT NULL COMMENT '집행등록 처리 결과 코드',
  `process_result_mssage` varchar(4000) DEFAULT NULL COMMENT '집행등록 처리 결과 메시지',
  `exrlt_code` varchar(3) DEFAULT NULL COMMENT '이체결과 처리 결과 코드',
  `exrlt_mssage` varchar(4000) DEFAULT NULL COMMENT '이체결과 처리 결과 메시지',
  `insert_id` varchar(10) DEFAULT NULL COMMENT '입력자',
  `insert_dt` varchar(8) DEFAULT NULL COMMENT '입력일자',
  `insert_ip` varchar(30) DEFAULT NULL COMMENT '입력 IP',
  `modify_id` varchar(10) DEFAULT NULL COMMENT '수정자',
  `modify_dt` datetime DEFAULT NULL COMMENT '수정일자',
  `modify_ip` varchar(30) DEFAULT NULL COMMENT '수정 IP',
  `json_abdocu_h` longtext COMMENT '집행등록 row json 문자열',
  `json_abdocu_d` longtext COMMENT '집행등록 상세 row json 문자열',
  PRIMARY KEY (`anbojo_seq`,`d_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `t_ex_anbojo_abdocu_b` (
  `anbojo_seq` int(11) NOT NULL COMMENT '국고보조 시퀀스',
  `d_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 시퀀스',
  `b_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 시퀀스',
  `erp_comp_seq` varchar(4) NOT NULL COMMENT 'ERP 회사 코드',
  `erp_comp_name` varchar(32) NOT NULL COMMENT 'ERP 회사 명칭',
  `mosf_gisu_dt` varchar(8) NOT NULL COMMENT '집행등록 결의일자 ( 집행등록 요청의 품의일자 ( CNSUL_DE ) )',
  `mosf_gisu_sq` int(11) DEFAULT NULL COMMENT '집행등록 결의순번 ( 집행등록 요청의 품의번호 ( CNSUL_NO ) )',
  `mosf_bg_sq` int(11) DEFAULT NULL COMMENT '집행등록 비목순번',
  `cntc_sn` int(11) DEFAULT NULL COMMENT '연계 순번 ( 파일생성시 update ( 파일내 데이터를 구별하는 유일한 식별자, 순차적 기재 ) )',
  `cntc_job_process_code` varchar(2) DEFAULT NULL COMMENT '연계 업무처리 코드 ( 파일생성시 update ( 등록 : C / 수정 : U / 삭제 : D ) )',
  `intrfc_id` varchar(20) DEFAULT NULL COMMENT '인터페이스 ID ( IF-EXE-ERP-0074 )',
  `trnsc_id` varchar(50) DEFAULT NULL COMMENT '트랜잭션 ID ( 파일생성시 update )',
  `file_id` varchar(64) DEFAULT NULL COMMENT '파일 ID ( 파일생성시 update ( 첨부파일이 존재할 경우 ) )',
  `cntc_creat_dt` varbinary(14) DEFAULT NULL COMMENT '연계 생성 일시 ( 파일생성시 udpate )',
  `cntc_trget_sys_code` varchar(6) NOT NULL COMMENT '연계 대상 시스템 코드 ( 디폴트 : ANBOJO_SYSTEM_CD.SYSTEM_CD )',
  `excut_cntc_id` varchar(20) NOT NULL COMMENT '집행연계 ID ( 집행건별 유일 KEY ( CO_CD + MOSF_GISU_DT + MOSF_GISU_SQ ) )',
  `asstn_taxitm_code` varchar(5) DEFAULT NULL COMMENT '보조세목코드 ( 보조비목세목 ( T_CMM_ASSTM_EXPITM_TAXITM ), 공통관리 인터페이스 ( 공통관리코드 ) )',
  `excut_taxitm_cntc_id` varchar(20) DEFAULT NULL COMMENT '집행비목세목연계 ID ( CO_CD+MOSF_GISU_DT+MOSF_GISU_SQ+MOSF_BG_SQ )',
  `taxitm_fnrsc_cnt` varchar(5) DEFAULT NULL COMMENT '세목별재원건수 ( 집행비목세목연계ID에 해당하는 _T 건수 )',
  `prdlst_nm` varchar(100) DEFAULT NULL COMMENT '품목',
  `insert_id` varchar(10) DEFAULT NULL COMMENT '입력자',
  `insert_dt` datetime DEFAULT NULL COMMENT '입력일자',
  `insert_ip` varchar(15) DEFAULT NULL COMMENT '입력 IP',
  `modify_id` varchar(10) DEFAULT NULL COMMENT '수정자',
  `modify_dt` datetime DEFAULT NULL COMMENT '수정일자',
  `modify_ip` varchar(15) DEFAULT NULL COMMENT '수정 IP',
  `json_abdocu_b` longtext COMMENT '비목정보 row json 문자열',
  PRIMARY KEY (`anbojo_seq`,`d_seq`,`b_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `t_ex_anbojo_abdocu_pay` (
  `anbojo_seq` int(11) NOT NULL COMMENT '국고보조 시퀀스',
  `d_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 시퀀스',
  `b_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 시퀀스',
  `t_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 재원정보 시퀀스',
  `p_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 재원정보 인력정보 시퀀스',
  `erp_comp_seq` varchar(4) NOT NULL COMMENT 'ERP 회사 코드',
  `erp_comp_name` varchar(32) DEFAULT NULL COMMENT 'ERP 회사 명칭',
  `mosf_gisu_dt` varchar(8) NOT NULL COMMENT '집행등록 결의일자 ( 집행등록 요청의 품의일자(CNSUL_DE) )',
  `mosf_gisu_sq` int(11) DEFAULT NULL COMMENT '집행등록 결의순번 ( 집행등록 요청의 품의번호(CNSUL_NO) )',
  `mosf_bg_sq` int(11) DEFAULT NULL COMMENT '집행등록 비목순번',
  `mosf_ln_sq` int(11) DEFAULT NULL COMMENT '집행등록 재원순번',
  `cntc_sn` int(11) DEFAULT NULL COMMENT '연계순번 ( 파일내 데이터를 구별하는 유일한 식별자_순차적 기재, 집행인력등록 요청 시 UPDATE )',
  `cntc_job_process_code` varchar(2) DEFAULT NULL COMMENT '연계업무처리코드 ( C.등록 U.수정 D.삭제 )',
  `intrfc_id` varchar(20) DEFAULT NULL COMMENT '인터페이스 ID',
  `trnsc_id` varchar(50) DEFAULT NULL COMMENT '트랜잭션 ID',
  `file_id` varchar(64) DEFAULT NULL COMMENT '파일 ID ( 파일생성시 update (첨부파일이 존재할 경우) )',
  `cntc_creat_dt` varchar(14) DEFAULT NULL COMMENT '연계생성일시',
  `cntc_trget_sys_code` varchar(6) DEFAULT NULL COMMENT '연계대상시스템코드',
  `bsnsyear` varchar(4) NOT NULL COMMENT '사업연도 ( ANBOJO_ABDOCU의 해당 값 )',
  `ddtlbz_id` varchar(20) NOT NULL COMMENT '상세내역사업 ID ( ANBOJO_ABDOCU의 해당 값 )',
  `exc_instt_id` varchar(12) NOT NULL COMMENT '수행기관 ID ( ANBOJO_ABDOCU의 해당 값 )',
  `excut_cntc_id` varchar(20) NOT NULL COMMENT '집행연계 ID ( 집행건별 유일KEY (CO_CD+MOSF_GISU_DT+MOSF_GISU_SQ) )',
  `excut_taxitm_cntc_id` varchar(20) NOT NULL COMMENT '집행비목세목연계 ID ( CO_CD+MOSF_GISU_DT+MOSF_GISU_SQ+MOSF_BG_SQ )',
  `hnf_regist_sn` varchar(5) NOT NULL COMMENT '인력등록순번 ( 동일 키값에서 MAX+1 )',
  `hnf_nm` varchar(300) DEFAULT NULL COMMENT '인력명(기타소득/사원명) ( ABDOCU_T.TR_NM으로 활용 )',
  `hnf_lsft_no` varchar(13) DEFAULT NULL COMMENT '인력실명번호',
  `prrt` int(11) DEFAULT NULL COMMENT '참여율',
  `partcptn_begin_de` varchar(8) DEFAULT NULL COMMENT '참여시작일자',
  `partcptn_end_de` varchar(8) DEFAULT NULL COMMENT '참여종료일자',
  `pymnt_amount` decimal(15,0) DEFAULT NULL COMMENT '지급총금액',
  `process_result_code` varchar(3) DEFAULT NULL COMMENT '처리결과코드 ( 등록결과 수신정보  )',
  `process_result_mssage` varchar(2000) DEFAULT NULL COMMENT '처리결과메시지 ( 등록결과 수신정보 )',
  `pay_fg` varchar(2) DEFAULT NULL COMMENT '지급처구분 ( 1.급여 2.기타소득 3.사업소득 )',
  `etctr_cd` varchar(15) DEFAULT NULL COMMENT '기타소득자 거래처코드 ( 더존 사원/기타소득/사업소득자 코드 (결의서 ABDOCU_T.TR_CD로 활용) )',
  `etcrvrs_ym` varchar(6) DEFAULT NULL COMMENT '급여/기타소득 귀속년월',
  `etcdiv_cd` varchar(4) DEFAULT NULL COMMENT '기타/사업소득자 사업장코드',
  `etcdummy1` varchar(20) DEFAULT NULL COMMENT '기타소득 소득구분 OR 자료 불러오기 구분 ( 1.처리된 급여/사업소득자료불러오기 2.기타소득자료불러오기 기타소득자코드도움시 소득구분 값(디폴트76) )',
  `etcdummy2` varchar(4) DEFAULT NULL COMMENT '기타소득 신고귀속년 ( 기타소득에만 해당 )',
  `ndep_am` decimal(17,4) DEFAULT NULL COMMENT '기타소득 필요경비금액',
  `inad_am` decimal(17,4) DEFAULT NULL COMMENT '기타소득 소득금액',
  `intx_am` decimal(17,4) DEFAULT NULL COMMENT '급여/기타/사업 소득세액',
  `rstx_am` decimal(17,4) DEFAULT NULL COMMENT '급여/기타/사업 주민세액',
  `wd_am` decimal(17,4) DEFAULT NULL COMMENT '급여 소득공제액 ( 급여자료에만 해당 )',
  `etcpay_dt` varchar(8) DEFAULT NULL COMMENT '기타/사업소득 지급일자 ( F3.처리된 기타/사업소득자료 불러오기시에만 반영 )',
  `et_yn` varchar(2) DEFAULT NULL COMMENT '소득 처리방법 ( 0.처리된 기타소득 불러오기 1.기타소득자 코드도움 5.처리된 급여데이터 불러오기 9.처리된 사업소득 불러오기 ''''.사원코드도움, 사업소득자코드도움 )',
  `etcdata_cd` varchar(4) DEFAULT NULL COMMENT '기타소득자구분코드 ( G.거주자 기타소득자 F.거주자 사업소득자 BI.비거주자 사업/기타 ''''.사원코드도움,처리된 급여데이터 불러오기 )',
  `etctax_rt` decimal(10,4) DEFAULT NULL COMMENT '미사용 컬럼',
  `hife_am` decimal(17,4) DEFAULT NULL COMMENT '국민연금',
  `nape_am` decimal(17,4) DEFAULT NULL COMMENT '건강보험',
  `ddct_am` decimal(17,4) DEFAULT NULL COMMENT '고용보험',
  `noin_am` decimal(17,4) DEFAULT NULL COMMENT '장기요양',
  `wd_am2` decimal(17,4) DEFAULT NULL COMMENT '급여 기타세액',
  `etcrate` decimal(5,2) DEFAULT NULL COMMENT '필요경비율 ( 기타소득자 그외 필요경비있는경우(62번)에 한하여 필요경비율 저장 )',
  `gw_state` varchar(2) DEFAULT NULL COMMENT '그룹웨어 상태값',
  `gw_id` varchar(20) DEFAULT NULL COMMENT '전자결재 작업자',
  `sing_fg` varchar(3) DEFAULT NULL COMMENT '인력등록결과코드',
  `sing_nm` varchar(2000) DEFAULT NULL COMMENT '인력등록결과메시지',
  `insert_id` varchar(10) DEFAULT NULL COMMENT '입력자',
  `insert_dt` datetime DEFAULT NULL COMMENT '입력일자',
  `insert_ip` varchar(15) DEFAULT NULL COMMENT '입력 IP',
  `modify_id` varchar(10) DEFAULT NULL COMMENT '수정자',
  `modify_dt` datetime DEFAULT NULL COMMENT '수정일자',
  `modify_ip` varchar(15) DEFAULT NULL COMMENT '수정 IP',
  PRIMARY KEY (`anbojo_seq`,`d_seq`,`b_seq`,`t_seq`,`p_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `t_ex_anbojo_abdocu_t` (
  `anbojo_seq` int(11) NOT NULL COMMENT '국고보조 시퀀스',
  `d_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 시퀀스',
  `b_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 시퀀스',
  `t_seq` int(11) NOT NULL COMMENT '국고보조 집행등록 비목정보 재원정보 시퀀스',
  `erp_comp_seq` varchar(4) NOT NULL COMMENT 'ERP 회사 코드',
  `erp_comp_name` varchar(32) DEFAULT NULL COMMENT 'ERP 회사 명칭',
  `mosf_gisu_dt` varchar(8) NOT NULL COMMENT '집행등록 결의일자 ( 집행등록 요청의 품의일자(CNSUL_DE) )',
  `mosf_gisu_sq` int(11) DEFAULT NULL COMMENT '집행등록 결의순번 ( 집행등록 요청의 품의번호(CNSUL_NO) )',
  `mosf_bg_sq` int(11) DEFAULT NULL COMMENT '집행등록 비목순번',
  `mosf_ln_sq` int(11) DEFAULT NULL COMMENT '집행등록 재원순번',
  `gisu_dt` varchar(8) DEFAULT NULL,
  `gisu_sq` int(11) DEFAULT NULL,
  `cntc_sn` int(11) DEFAULT NULL COMMENT '연계순번 ( 파일생성시 update (파일내 데이터를 구별하는 유일한 식별자_순차적 기재) )',
  `cntc_job_process_code` varchar(2) DEFAULT NULL COMMENT '연계업무처리코드 ( 파일생성시 update (C: 등록, U: 수정, D: 삭제) )',
  `intrfc_id` varchar(40) DEFAULT NULL COMMENT '인터페이스 ID ( IF-EXE-ERP-0074 )',
  `trnsc_id` varchar(100) DEFAULT NULL COMMENT '트랜잭션 ID ( 파일생성시 update )',
  `file_id` varchar(128) DEFAULT NULL COMMENT '파일 ID ( 파일생성시 update (첨부파일이 존재할 경우) )',
  `cntc_creat_dt` varchar(28) DEFAULT NULL COMMENT '연계생성일시 ( 파일생성시 update )',
  `cntc_trget_sys_code` varchar(12) NOT NULL COMMENT '연계대상시스템코드 ( 디폴트 (ANBOJO_SYSTEM_CD.SYSTEM_CD) )',
  `excut_cntc_id` varchar(40) NOT NULL COMMENT '집행연계 ID ( 집행건별 유일KEY (CO_CD+MOSF_GISU_DT+MOSF_GISU_SQ) )',
  `excut_taxitm_cntc_id` varchar(40) DEFAULT NULL COMMENT '집행비목세목연계 ID ( CO_CD+MOSF_GISU_DT+MOSF_GISU_SQ+MOSF_BG_SQ )',
  `fnrsc_se_code` varchar(20) DEFAULT NULL COMMENT '재원구분코드 ( 재원구분코드:1220 공통관리 인터페이스(공통관리코드) )',
  `mgt_cd` varchar(20) DEFAULT NULL COMMENT '프로젝트 ( 결의서발행 시 활용(ABDOCU.MGT_CD) )',
  `bottom_cd` varchar(20) DEFAULT NULL COMMENT '하위사업',
  `abgt_cd` varchar(20) DEFAULT NULL COMMENT '예산과목 ( 결의서발행 시 활용(ABDOCU_B.ABGT_CD) )',
  `btr_cd` varchar(20) DEFAULT NULL COMMENT '입/출금계좌 거래처 코드 ( 결의서발행 시 활용(ABDOCU.BTR_CD) )',
  `splpc` decimal(15,0) DEFAULT NULL COMMENT '공급가액',
  `vat` decimal(15,0) DEFAULT NULL COMMENT '부가가치세',
  `sum_amount` decimal(15,0) DEFAULT NULL COMMENT '합계금액',
  `insert_id` varchar(10) DEFAULT NULL COMMENT '입력자',
  `insert_dt` datetime DEFAULT NULL COMMENT '입력일자',
  `insert_ip` varchar(15) DEFAULT NULL COMMENT '입력 IP',
  `modify_id` varchar(10) DEFAULT NULL COMMENT '수정자',
  `modify_dt` datetime DEFAULT NULL COMMENT '수정일자',
  `modify_ip` varchar(15) DEFAULT NULL COMMENT '수정 IP',
  `json_abdocu_t` longtext COMMENT '재원정보 JSON',
  PRIMARY KEY (`anbojo_seq`,`d_seq`,`b_seq`,`t_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `t_ex_anbojo_emp` (
  `seq` int(11) NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `comp_seq` varchar(32) DEFAULT NULL COMMENT '회사 시퀀스',
  `comp_name` varchar(128) DEFAULT NULL COMMENT '회사 명칭',
  `erp_comp_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 회사 코드',
  `erp_comp_name` varchar(128) DEFAULT NULL COMMENT 'ERP 회사 명칭',
  `biz_seq` varchar(32) DEFAULT NULL COMMENT '사업장 시퀀스',
  `biz_name` varchar(128) DEFAULT NULL COMMENT '사업장 명칭',
  `erp_biz_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 사업장 코드',
  `erp_biz_name` varchar(128) DEFAULT NULL COMMENT 'ERP 사업장 명칭',
  `dept_seq` varchar(32) DEFAULT NULL COMMENT '부서 시퀀스',
  `dept_name` varchar(128) DEFAULT NULL COMMENT '부서 명칭',
  `erp_dept_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 부서 코드',
  `erp_dept_name` varchar(128) DEFAULT NULL COMMENT 'ERP 부서 명ㅊ이',
  `emp_seq` varchar(32) DEFAULT NULL COMMENT '사원 시퀀스',
  `emp_name` varchar(128) DEFAULT NULL COMMENT '사원 명',
  `erp_emp_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 사원 번호',
  `erp_emp_name` varchar(128) DEFAULT NULL COMMENT 'ERP 사원 명',
  `erp_pc_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 회계단위 코드',
  `erp_pc_name` varchar(128) DEFAULT NULL COMMENT 'ERP 회계단위 명칭',
  `erp_cc_seq` varchar(32) DEFAULT NULL COMMENT 'ERP 코스트센터 코드',
  `erp_cc_name` varchar(128) DEFAULT NULL COMMENT 'ERP 코스트센터 명칭',
  `create_seq` varchar(32) DEFAULT NULL COMMENT '최초 작성자',
  `create_date` datetime DEFAULT NULL COMMENT '최초 작성일',
  `modify_seq` varchar(32) DEFAULT NULL COMMENT '최종 수정자',
  `modify_date` datetime DEFAULT NULL COMMENT '최종 수정일',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB AUTO_INCREMENT=400 DEFAULT CHARSET=utf8;

/* --------------------------------------------------------------------------------------------- */
/* 여기까지 배포 완료 ( 배포일 : 2017. 07. 12. ) - 김상겸 */
/* --------------------------------------------------------------------------------------------- */
/* --------------------------------------------------------------------------------------------- */
/* 여기까지 배포 완료 ( 배포일 : 2017. 07. 18. ) - 김상겸 */
/* --------------------------------------------------------------------------------------------- */
/* --------------------------------------------------------------------------------------------- */
/* 여기까지 배포 완료 ( 배포일 : 2017. 08. 10. ) - 신재호 */
/* --------------------------------------------------------------------------------------------- */