/* iCUBE ACARD_SUNGIN 기준 거래처 일괄생성 쿼리  */
/* iCUBE 만 지원. 고객사의 클레임으로 에이전트 생성 */
/* 고객사 : 워터웨이플러스 */

DECLARE @LANGKIND nvarchar(3)
DECLARE @CO_CD nvarchar(4)
DECLARE @TR_FG nvarchar(1)
DECLARE @TR_NM nvarchar(60)
DECLARE @REG_NB nvarchar(30)
DECLARE @CEO_NM nvarchar(30)
DECLARE @BUSINESS nvarchar(40)
DECLARE @JONGMOK nvarchar(40)
DECLARE @TEL nvarchar(20)
DECLARE @ZIP nvarchar(7)
DECLARE @DIV_ADDR1 nvarchar(150)
DECLARE @ADDR2 nvarchar(150)

DECLARE CUR CURSOR FOR
	SELECT	'KOR' AS LANGKIND
			, CO_CD
			, '1' AS TR_FG
			, MAX(CHAIN_NAME) AS TR_NM
			, CHAIN_REGNB AS REG_NB
	FROM	ACARD_SUNGIN
	WHERE	ISNULL(CHAIN_REGNB, '') != ''
	AND		ISS_DT >= CONVERT(NVARCHAR(8), DATEADD(DAY, -5, GETDATE()), 112)
	GROUP	BY CO_CD, CHAIN_REGNB
OPEN CUR
FETCH NEXT FROM CUR INTO @LANGKIND, @CO_CD, @TR_FG, @TR_NM, @REG_NB
WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXECUTE [DZICUBE].[dbo].[USP_C0MMON_GET_TR_CD_FOR_NOT_EXIST_INSERT] 
	   @LANGKIND
	  ,@CO_CD
	  ,@TR_FG
	  ,@TR_NM
	  ,@REG_NB
	  ,@CEO_NM
	  ,@BUSINESS
	  ,@JONGMOK
	  ,@TEL
	  ,@ZIP
	  ,@DIV_ADDR1
	  ,@ADDR2
	FETCH NEXT FROM CUR INTO @LANGKIND, @CO_CD, @TR_FG, @TR_NM, @REG_NB
END

CLOSE CUR
DEALLOCATE CUR