/* --------------------------------------------------------------------------------------------- */
/* Bizbox Version => 6.7 */
/* 여기까지 배포 완료 ( 배포일 : 2019. 01. 10. ) - 이준성 */
/* --------------------------------------------------------------------------------------------- */

INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_budgetInfo','예산내역','','예산내역','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_buyRes','구입과지출결의서','','구입과지출결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_callCons','품의서 불러오기','','품의서 불러오기','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_cash','현금','','현금','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_corpRes','공사집행지출결의서','','공사집행지출결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_debt','외상','','외상','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_deposit','예금','','예금','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_empAdd','사원등록','','사원등록','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_etc','기타','','기타','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_etcEarner','기타소득자','','기타소득자','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_expendCons','지출품의서','','지출품의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_expendRes','지출결의서','','지출결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_fellowRes','여입결의서','','여입결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_incomeRes','수입결의서','','수입결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_purchaseCons','구매품의서','','구매품의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_returnRes','반납결의서','','반납결의서','SYSTEM',SYSDATESYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_salaryRes','봉급지출결의서','','봉급지출결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_serviceCons','용역품의서','','용역품의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_serviceRes','용역과지출결의서','','용역과지출결의서','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_tax','과세','','과세','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_taxFree','면세','','면세','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_tradeInfo','거래처 정보','','거래처 정보','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_tripRes','여비지출결의서','','여비지출결의서','SYSTEM',SYSDATESYSDATE,'SYSTEM',SYSDATE,'');
INSERT IGNORE INTO `t_ex_langpack` (`comp_seq`, `lang_type`, `lang_code`, `basic_name`, `langpack_code`, `lang_name`, `create_seq`, `create_date`, `modify_seq`, `modify_date`, `tooltip`) VALUES('EXP_LANGPACK','kr','ex_vendorName','거래처명','','거래처명','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'');